language: node_js
node_js:
- node
- '8'
- '6'

# https://docs.travis-ci.com/user/customizing-the-build/#Fast-Finishing
matrix:
  fast_finish: true

script: npm test -- --coverage --verbose

after_success:
  - |
    $(npm bin)/set-up-ssh \
      --key "$encrypted_1001587ab084_key" \
      --iv "$encrypted_1001587ab084_iv" \
      --path-encrypted-key ".travis/github_deploy_key.enc"

    # --commands is unecessary but required, so it's effectively a no-op
    # --branch makes sure this only happens on master
    $(npm bin)/commit-changes \
      --commands "echo committing changes" \
      --commit-message "Bundled output for commit $TRAVIS_COMMIT [skip ci]" \
      --branch "master"

env:
  global:
    - secure: "JdYaM+SoHMay0sR5aqTzAt7BM7W/v8HbuXm14nEfUbXMhkDQi44qyAJCh35qLw/Zb8cWgOSQsMUQXoyLSsfTNDbml6UrVJC6t6EQ2bGLx+Wj6+PNyE1qm/BZDI9TIWD8oZ+95jNVfpjFzmLUTqMmFm    4fdXnDV76orGYfMN2IPBOoK3Lh2jicSh5Cxy0DvL8Y4QxsySO8kGyzKGetFZnrsvg3eABDSjI5Hp99DUmMpbD8LyEx68mYwnFpBo6Xf36AoTvpk5FDYXVmM1a5LTlluOKYv5ccBgBkvhA+W3uwNQ4ENWuP2dWkmdB4LyEfBRad7jDUXx8doI8jJYHURRKUZRNF5gFHhYVwbe3oJy4ggBoN9W+zTENtb6811JDv5gaqEayBPoO74N67pZxhPomWPWA77d5Zy0g8vsIeJd8TqRgiaQ0+BVG4X1pNzQwu5EKkekZAerU1yG/jTSzfB6T7vN2P2ND2MOmRteYezsH1aJjePCsjH/+Rmb8xTgwEMGHNfQawBqUtPg3mONnC3qxTmmRbK+7DadNplI92CtLJ7pRJV2lrkBnzN2we0gt2Vh/Ydo62WCrrJ/5eTZnsHcy61W5CUNIvbTzndCmzsZPR5K9+OAfW5YzYhYQAOhJgZtFkESGYWz9WWYLKcy0l2YTw2VVdLa3GsYlrmyWpy+oefFY="

deploy:
  - provider: npm
    email: npm@patcavit.com
    skip_cleanup: true
    api_key:
      secure: "lCmeee46fKI90zXqquXmsCLop1/rufRwskLH4lKRTJz7FjTRFzsPrap8EBoMTzbpRaRc2hvlxQF+Lmcs2JSacuypCsV6jWO9fILDmyl+f/lAR55sUTd7nDaEan77Vo2iFHXZdRbmeukT0+EkikKkB5j9qf4DZLS0ye67UvbqQO2o+8/d0UUZ89Excv0xaY1SQMU9OWB6RmMCO78sqe4vOVPPJ57SjisMzwGYU2ROPuQ0bmOhqp5qumN3dShqUgryv1YNrBveWkacRjgIa4gZz+E/pgLqC3/Nw8vtXgtRg1B+X2Hw2THpgT5SdU1UFZ7DPehMhMk0ObOJUNC0A0+nn5UuUWbtXppGM0uYh4wRwuvSLV8KeP82cVRPTocPaXKieZSQxU/BNQBNfP+4Wa8Z5jV2kMoB9d2LB+0XzFKnmr5GiPq7mIAf9HvHLj1k7wb8wugOdtgtnXTNxNdOTRrTIHMulyxtsh6DLaArjXLqGEsYGBLdJU9RfVLtFxD5XByWWfAjynioPn1KUz6mWgTICw7hZwk0VcFDFaYkIKasiBS1LbXVf1M3qVtW9UHsCtFaSkmpCS7S3QDgfBdRlDcIuya1VJFPLCRKaXOHJsLtBjTPff0eixbTHl0G2oe5Dst9SBksglY416L9/oDUufxgfMy5Xl6RV4zamQp0X1gnOrE="
    on:
      tags: true
      repo: tivac/aws-sig
